### ISSUE TITLE
Error at starting

### ISSUE THREAD

**Issue by Willena** [cheald/murmur-manager#4]
Hi, 
I am interested by your project but I can't make it working, I face this error
```
./manage-ice.rb
ruby: Util.cpp:479: void IceRuby::hashIterate(VALUE, IceRuby::HashIterator&): Assertion `rb_type((VALUE)(h)) == RUBY_T_HASH' failed.
Abandon
```

I have installed Ice by doing gem install zeroc-ice and ruby by doing apt-get install ruby.
As writen in ice-howto.txt when typing 
irb, ....
ice is working.

So I d'ont know what could cause this error.

**Comment by kyle142** [comment]
I have exactly the same problem

Kyle@server2:~/murmur-manager$ irb
irb(main):001:0> require 'Ice'
=> true
irb(main):002:0> quit

Kyle@server2:~/murmur-manager$ ./manage-ice.rb list                             ruby: Util.cpp:479: void IceRuby::hashIterate(VALUE, IceRuby::HashIterator&): Assertion `rb_type((VALUE)(h)) == RUBY_T_HASH' failed.
Aborted

**Comment by kyle142** [comment]
Ah, I'm just having a look at the date, unsure if package maintainer is still working on it, hopefully... would be a really handy tool to use. If anyone knows of a similar program, would be much appreciated.
